env:
  browser: true
  es2021: true
extends: airbnb-base
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  import/extensions:
    - error
    - js: always
  no-console: 0
  no-underscore-dangle: [2, {"allow": ["__filename", "__dirname"]}]
